config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  root 'static_pages#home'

  get 'help'      =>    'static_pages#help'
  
  get 'about'     =>    'static_pages#about'
  
  get 'contact'   =>    'static_pages#contact'
  
  get 'signup'    =>    'users#new'

  

end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def hello
    render text: "Hey!"
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else 
      page_title + " | " + base_title
    end
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <li><%= link_to "Log in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>

</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
    <h>This is the About Page for Burton Cooke's Sample App</h>
    <p>
      The <a href="http://www.railstutorial.org"><em>Ruby on Rails Tutorial</em></a> is a 
      <a href="http://www.railstutorial.org/book">book</a> and <a href="http://screencasts.railstutorial.org">screencast series</a>
      to be used for web development with <a href="http://rubyonrails.org">Ruby on Rails</a>.  
      This is the about page for the sample app.
    </p>
 

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/#contact">contact page</a>.
  And contact Burton Cooke at burtoncooke@yahoo.com.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
    <h1>Need Help with the App?</h1>
    <p>
      Check out the <a href="http://www.railstutorial.org/#help">Ruby on Rails Tutorial Help section</a>.
      For help with the sample app, check out the <a href="http://www.railstutorial.org/book"><em>Ruby on Rails 3rd Edition</em>book</a>.
    </p>
  

app/views/static_pages/home.html.erb
    <div class="center jumbotron">
      <h1>Welcome to Burton Cooke's Sample App Home Page!!</h1>
      
      <h2>
        This is the website for the <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a> sample application!!!!
      </h2>
      
      <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
      
    </div>
    
    <%= link_to image_tag("rails.png", alt: "Rails logo"),
                                      'http://rubyonrails.org' %>
      
 

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>